#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 26 02:39:09 2017

@author: shubhankar
"""
# Regression Template

# Importing the Libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 

# Importing the dataset
dataset = pd.read_csv("Position_Salaries.csv)
X = dataset.iloc[:, 1:2].values
y = dataset.iloc[:, 2].values

# Splittig the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_